### ISSUE TITLE
Path improvement.

### ISSUE THREAD

**Issue by lilezek** [Apostolique/Agar.io-bot#112]
There are some easy improvements that can be done to augment efficiency (I've get a bot that almost always reaches 250 points and it reached 600 at top).

Sadly I don't have the code clean and handy, but those points are (sorted by difficulty of implementation):

* 1º Don't follow enemies at early stages (that is less than 400 mass). They won't get caught the 90% of the time.
* 2º Prioritize cluster points far from edges.
* 3º Don't cluster food which is in radius of danger, as it will always try to undo the path done.
* 4º In case of full danger angle (that is, no angle is safe to flee) do 5th or 6th
* 5º If near a virus, hide inside if possible.
* 6º If not, clear the angles (lets start over again, thinking all angles are safe), but now only take in account the nearest danger.

**Comment by Apostolique** [comment]
TBH, I only think 3 will make things better I already have the code for that done since old versions were using that. I don't like 1 and 2 as I don't want to make any parts of the code based on a hard coded size value. If something is impossible to catch, then the food calculation will simply ignore them if it's done right. (There is a threshold where if something has a high value but the travel cost is too high, closer smaller stuff will end up being worth more as they don't have as much of a travel cost.) In other words, it's not a problem of not chasing enemies that can't be caught, but a problem related to how food is valued and that doesn't change no matter what stage in the game you're at.

5 is worth doing, but for an other reason than the one you stated. 6 is a good idea, but it's not actually the right way to do it. The goal when you are completely surrounded is to try to find a way towards open spaces. Simply trying to run away from the closest enemy won't achieve that.

**Comment by lilezek** [comment]
I think 1º point increases at very early stage the score quickly. If you don't want it to be hardcoded, just don't follow food which moves at a speed to opposite direction from where you are, or something like that, but if the bot keeps moving toward enemies it will just lose that time.
