### ISSUE TITLE
Can't change name

### ISSUE THREAD

**Issue by Gfiti** [Apostolique/Agar.io-bot#313]
Ever since the last version (the one that fixed the respawning) it won't let me change the name.

When I load the page it almost instantly jumps into the game. Even when I seem to be fast enough to paste a name in, it still won't change.

Also, the bot seems to behave kinda wonky sometimes. Sometimes when escaping from a slightly bigger cell it goes back and forth and ends up going into the cell seemingly on intent. Sometimes it seems to target stuff that is way out of the render range instead of the particles or cells around you.

**Comment by Apostolique** [comment]
To change the name, make sure you press the Play button after you typed your name in. If you don't have enough time to type it in, just press ESC, type it in, then go die.

Right now it acts wonky because I didn't work on the bot for the past 2 - 3 weeks. I'm settled in my new house now so I should be able to resume work on this. (Still got a few things to do, but otherwise the big stuff is done.)

**Comment by Gfiti** [comment]
Doesn't work for me. The menu shows up, I enter name and press play, but the bots just keeps going in the background. And when it dies and respawns it still got the default name
