### ISSUE TITLE
no auto restart

### ISSUE THREAD

**Issue by Titaniumtown** [Apostolique/Agar.io-bot#317]
need! auto restart!!!!!!!!!!!!!!!!!!!!

**Comment by Drflash55** [comment]
What do you mean by, No Auto Restart and that it need's it?
The bot has the auto restart thing in-built so that when you die, you start on a new cell automatically.

Do you mean to say that it's broken? If so, try re-installing it, and if it doesn't work, consult Apostolique about the problem.

**Comment by Apostolique** [comment]
You might need to log out of your facebook account, then log back in.

**Comment by stefnotch** [comment]
Ok, I found the source of the bug. I am not sure what is wrong with the IF statement though...I added some comments to the code! (Seriously, add more comments to the code. It's almost as if you don't want anybody else to improve it.)

        if (getPlayer().length == 0 && !reviving && ~~(getCurrentScore() / 100) > 0) {
            console.log("Dead: " + ~~(getCurrentScore() / 100)); **//Works perfectly**
            apos('send', 'pageview');
        }

        if (getPlayer().length == 0) { **//Also works**
            if ((d.localStorage.wannaLogin != null && fbDone) || d.localStorage.wannaLogin == null) { **//Right here seems to be a bug**
                console.log("Revive " + d.localStorage.wannaLogin);
                setNick(originalName);
                reviving = true;
            } else { **//This is what happens**
                console.log("Wait!");
            }
        } else if (getPlayer().length > 0 && reviving) {
            reviving = false;
        }

**Comment by Apostolique** [comment]
I promise I'll comment everything!

````
((d.localStorage.wannaLogin != null && fbDone) || d.localStorage.wannaLogin == null)
````

This first part can probably be simplified to:
````
d.localStorage.wannaLogin && fbDone
````
This simply means if you are supposed to be connected to Facebook AND you also are already connected to Facebook, then start the game.

The second part could be simplified to:
````
!d.localStorage.wannaLogin
````
And that simply means: If you are only playing as a guest, then you can just start right away.

The problem comes when people are playing using the loader.user.js in some cases, the system has the time to connect to Facebook and cache it in locaStorage.loginCache before the launcher.user.js code even has the time to get called. This makes the variable "fbDone" never become true.

There's a little conflict though (or perhaps there isn't any and it's all in my head) if the Facebook login is cached doesn't mean that it's okay to start the game,

**Comment by stefnotch** [comment]
Uhm, I guess I got it! So, is this correct (Oversimplified): The bot got a facebook connect test/function just like agar.io. Depending on who is quicker, it may or may not work.

Oh, and I guess I will make a fork of this AWESOME project. A suicidal one that only cares about getting you to level 9001! (Over 9000...hehe)

**Comment by Apostolique** [comment]
I think I should make a wiki of all the important forks. Before, I was able to check the network graph, but now that there are too many forks, it's almost impossible to find the ones that people are working on.

And you're right, if I understand it correctly, it's a contest of who is quicker. (Well, I could just ignore Facebook and let my bot auto start like it used to. On the first spawn, you'd still be size 10 (Since my auto spawn is faster than Facebook), but after your first death, you'd respawn with the correct Facebook size.) I could also put a timer, but in my mind, a timer is flawed by nature.

**Comment by Titaniumtown** [comment]
thx guys!

**Comment by stefnotch** [comment]
Ok, amazing! :D
Though, wouldn't it be possible to call the "kill"/"dead" function that agar.io has? (Even if it doesn't actually end up killing you, just get the relevant code to run. Maybe it has to restart afterwards?)
