### ISSUE TITLE
Bot movements not efficient

### ISSUE THREAD

**Issue by stanfordude** [Apostolique/Agar.io-bot#318]
Currently, the bot will travel towards the nearest source of food, which is often a less efficient way to travel. Try implementing a Traveling Salesman algorithm to maximize movement efficiency towards food, that way the bot might travel a little longer to get to a cluster of food instead of a bunch of single pieces.

**Comment by Gjum** [comment]
The problem with using such graph algorithms is that
- the bot only knows a limited part of the world, and
- the world changes rapidly, changing the "best path" very often.

**Comment by stanfordude** [comment]
But even with those limitations, shouldn't a graph algorithms contain the most efficient results that we are capable of knowing of? Also, I agree that the best path would change constantly, but it shouldn't take that much longer to compute the new best path since we only see a very small world. Do you still think the nearest-neighbor heuristic is the best option?

**Comment by Gjum** [comment]
It isn't. Alternatives started to be discussed [here](https://github.com/Apostolique/Agar.io-bot/issues/155#issuecomment-118451836).

**Comment by Apostolique** [comment]
My formula already doesn't go for the nearest food. It's a [food value] - [distance] formula. If something is really worth it, then the bot won't bother with the closer stuff.

Keep in mind though that you're in an eating competition against everyone else. Closer stuff should by nature be worth more since other people are likely to reach further stuff before you do.
