### ISSUE TITLE
lag 

### ISSUE THREAD

**Issue by bigwormm** [Apostolique/Agar.io-bot#348]
dose not split make it split

**Comment by stefnotch** [comment]
What do you mean? Does it lag/crash when you split? If it crashes, make sure you are using the latest update.

**Comment by Drflash55** [comment]
There was an issue with some of the older updates crashing because of incorrect scripting. If you update to the latest one, it should fix your splitting problem...

But, it would also be more helpful if you gave more details on the issue...
What exactly do you mean when you say it doesn't split? Do you mean that the bot doesn't split on it's own? If so, that's not implemented just yet... @Apostolique, has that on his todo list for getting the bot to split on it's own.

**Comment by bigwormm** [comment]
The bot dosenot split

**Comment by Apostolique** [comment]
I didn't code a splitting function yet.

**Comment by stefnotch** [comment]
@Drflash55 I am pretty sure that the splitting crash is my fault. :P

**Comment by henopied** [comment]
well it doesn't crash for me so he must have an old version
