### ISSUE TITLE
Passive / Deffensive AI - 

### ISSUE THREAD

**Issue by biels** [Apostolique/Agar.io-bot#402]
Would it be very difficult to implement an AI that aims to survive for as long as it can (while eating food from the ground and eventually little cells)? By this I mean increasing the danger radius for big cells and prioritizing food collection. The cell would aim to be as far as it can from every cell bigger than him as oposed to giving a specific radius to each threatening cell.

If the AI behaves this way it should get to the top of the leaderboard everytime it plays since there is no more efficient / secure way to do it, just it isn't the most time effective. You would be trading time for risk of starting over. 
In fact I can play better, last longer and get higher on the ranking than the bot the vast majority of the times.

Do you get my point?

**Comment by henopied** [comment]
It would run so much and mainly the mass decay would kick in before it gets enough mass in my opinion.

**Comment by Apostolique** [comment]
Yeah I get your point perfectly. There was a phase where the bot was exactly like that actually. It would run away from everything as soon as enemies were detected. It could easily survive 30 or 40 minutes but it wouldn't get very big because when you're running away most of the time, you don't really end up eating that much. Also since a server can hold 200 players, you have quite a lot of people to run away from.

That's when I decided to use a danger radius approach instead. It takes a bit more risks, but can get some really good runs.

(Having said that, the latest version doesn't run after people unless they are splitable and this makes it not that good I think.)

**Comment by henopied** [comment]
Maybe only put players in the food array when me -> enemy 1.3 and not me -> enemy 1.65 because only chasing people that you could split on might be good when in follow the mouse mode but in normal the player is much quicker than you and can quickly outrun you apposed to people just smaller than your size.

**Comment by biels** [comment]
Okay, it seems I didn't take the mass decay into account. Maybe my idea wasn't as good as I thought. But does the bot acctually split on enemies anyway?

**Comment by henopied** [comment]
It does not split yet.
