### ISSUE TITLE
Human issue

### ISSUE THREAD

**Issue by dfvollgas** [Apostolique/Agar.io-bot#456]
![agario bot](https://cloud.githubusercontent.com/assets/15805016/11114166/d4bd5d5a-8922-11e5-80c0-a837563b6661.png)

I am only able to select human mode in the dropdown list in the Agar.io menu.
No chance to hand over control to the bot. No matter how often I reinstall the bot or refresh the website the blob is always following the mouse. I am using Chrome 46.0.2490.80 and Agar.io bot 4.148
The bot is always showing turned on in the top left.

**Comment by Drflash55** [comment]
Hmm...

Have you tried updating to the latest version?
Usually this happens when your version is very outdated, or you screwed up something in the script that caused something to not function properly, so you activated the fallback mode.

Try re-installing bot.user.js and launcher.user.js and see if it works then...

**Comment by dfvollgas** [comment]
somehow I didn't have the bot.user.js installed so it is working fine now
I'll close the issue now.
