### ISSUE TITLE
Bottom Right Corner Causes Issues

### ISSUE THREAD

**Issue by silverchiren** [Apostolique/Agar.io-bot#52]
I found that the bot would occasionally get stuck and crash my browser when moving near/into the bottom right corner.

Attempted to fix it myself, changed
if (player[0].y > 11180 - 1000 && badAngles.length > 0) {
to
if (player[0].y > 10200 && badAngles.length > 0) {

Did so for both bottom wall and right wall, seemed to fix the issue. Not sure why.

Edit: Found that during gameplay the walls will seem to change position and move into the level, causing the above issue to repeat. Doing more research.

For bottom and right walls, chaged
var newY = 11180 + 100 + screenDistance();
to
var newX = 11350 + screenDistance();

Seems to be okay now.

**Comment by silverchiren** [comment]
Okay, lots of tweaking and experimenting later. Will just put here what I have the lines mentioned above set to

Left Wall:
if (player[0].x < 1000 && badAngles.length > 0) {
var newX = -300 - screenDistance();

Top Wall:
if (player[0].y < 1000 && badAngles.length > 0) {
var newY = -300 - screenDistance();

Right Wall:
if (player[0].x > 10200 && badAngles.length > 0) {
var newX = 11500 + screenDistance();

Bottom Wall:
if (player[0].y > 10200 && badAngles.length > 0) {
var newY = 11500 + screenDistance();

**Comment by Apostolique** [comment]
What you did can be considered a temporary fix. The real problem comes from the way I calculate angles when a player is inside an enemy. Right now, I create a fake enemy right on the other side of the wall. Sometimes, the enemy is too close to the wall and big enough to completely cover the bot. An easier way to fix this would be to simply move the wall enemy further behind the wall based on the size they are set to.

**Comment by silverchiren** [comment]
Yeah, my fix even stops working if the cell gets too big. I'm not sure how it's going to be actually fixed yet.
