### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by viziionary** [Apostolique/Agar.io-bot#639]
Sorry this isn't an issue at all, it's just that I'm working on an artificial intelligence program to play agar.io with neural networks, and I was trying to look into your code to see where you're grabbing the enemy data from. I found in your launcher where you're using a function `lb` to add human players to a list in the global scope, but for the life of me I couldnt find where you're getting location and size / radius data for the enemies and the player. 

Could you maybe point me in the right direction? Right nowmy approach is to force my own version of main_out.js to be loaded, but it doesnt seem like the necessary data is handled there.

**Comment by Apostolique** [comment]
This might be outdated too, but: http://agar.gcommer.com/index.php?title=Protocol

The blobs objects have a size variable that you can read. Example: https://github.com/Apostolique/Agar.io-bot/blob/master/bot.user.js#L888

Those values come from the network update: https://github.com/Apostolique/Agar.io-bot/blob/master/launcher.user.js#L610

Obviously, that code is pretty old. The game changed a lot since then and with the obfuscated code, it's pretty hard to find.

**Comment by viziionary** [comment]
@Apostolique right, well thanks. Yeah the obfuscated code makes it tough, but this info should help toward tracking down the right part.

**Comment by henopied** [comment]
Agar.io now has a new protocol with custom encryption and only a few have found this new protocol.
